### ISSUE TITLE
Regarding masking on the scores

### ISSUE THREAD

**Issue by IamAdiSri** [tebesu/CollaborativeMemoryNetwork#8]
Hi, could you please explain why masking has been carried out over the scores?

https://github.com/tebesu/CollaborativeMemoryNetwork/blob/2c55efdcb9f46f5d0e869cbbe68ba15eafc2a2cb/util/attention.py#L114

Also, what exactly is the significance of the minimum float value here? Specifically, why not use just 0s and 1s to mask?

https://github.com/tebesu/CollaborativeMemoryNetwork/blob/2c55efdcb9f46f5d0e869cbbe68ba15eafc2a2cb/util/attention.py#L65

**Comment by tebesu** [comment]
We mask out the positions where we do not want to apply the attention ie to deal with variable length sequences. 

Taking the softmax of 0 will add a lot to the attention weights since we take the exp. To exclude it we take the smallest value possible we can represent with a float 32 when computing the softmax. Hope this helps.

**Comment by IamAdiSri** [comment]
Thank you for the answer, it makes complete sense now.
